/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;
import java.awt.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Adan Nugraha 202031242
 */
public class BentukForm extends javax.swing.JFrame {
    private String Hasil;
    /**
     * Creates new form BentukForm
     */
    public BentukForm() {
        // mengecek sudah login atau belum
        // jika belum login akan di redirect ke form login
        if ("AKTIF".equals(crud.Session.getStatusLogin())) { 
            initComponents();
            textarea_hasil.disable();
        } else {
        // menutup form menu tanpa menutup aplikasi
        dispose();
        // memanggil form login
        LoginForm form = new LoginForm();
        form.setVisible(true);
        }
    }
    
    public void reset_text() {
        txt_angka1.setText("");
        txt_angka2.setText("");
    }
    
    private void polimorfisme(Bentuk[]B, double a, double b) {
        Hasil = "";
        for (Bentuk B1 : B) {
            B1.set_A(a);
            B1.set_B(b);
            B1.set_C();
            Hasil += B1.cetak() + "\n";
        }
    }
    
    public void cetakHasil(String Hasil) {
        textarea_hasil.setText(Hasil);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_angka1 = new javax.swing.JTextField();
        txt_angka2 = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_tutup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LUAS BENTUK");

        jLabel2.setText("Panjang/Alas/Diagonal 1");

        jLabel3.setText("Lebar/Tinggi/Diagonal 2");

        txt_angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_angka1ActionPerformed(evt);
            }
        });

        btn_hitung.setText("Hitung Luas");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_tutup.setText("Tutup");
        btn_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tutupActionPerformed(evt);
            }
        });

        jLabel4.setText("Hasil Luas Bentuk");

        textarea_hasil.setColumns(20);
        textarea_hasil.setForeground(Color.red);
        textarea_hasil.setFont(new Font("Serif",Font.BOLD,20));
        textarea_hasil.setRows(5);
        textarea_hasil.setSelectionColor(new java.awt.Color(255, 51, 51));
        jScrollPane1.setViewportView(textarea_hasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_hitung)
                                    .addGap(55, 55, 55)
                                    .addComponent(btn_reset)
                                    .addGap(65, 65, 65)
                                    .addComponent(btn_tutup))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_angka1)
                                    .addComponent(txt_angka2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_angka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_angka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hitung)
                    .addComponent(btn_reset)
                    .addComponent(btn_tutup))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_angka1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_angka1ActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        if (txt_angka1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Maaf, Panjang/Tinggi belum diisi!");
            txt_angka1.requestFocus();
        } else if (txt_angka2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Maaf, Lebar belum diisi!");
            txt_angka2.requestFocus();
        } else {
            String angka1 = txt_angka1.getText();
            Double angka_1 = Double.parseDouble(angka1);
            
            String angka2 = txt_angka2.getText();
            Double angka_2 = Double.parseDouble(angka2);
            
            Bentuk[]B = {
                new BentukPersegiPanjang(),
                new BentukJajarGenjang(),
                new BentukSegitiga(),
                new BentukLayangLayang(),
                new BentukBelahKetupat(),
            };
            
            polimorfisme(B,angka_1, angka_2);
            Bentuk bentuk = new Bentuk();
            bentuk.LogAktifitas(Session.getUserID(), "LUAS BENTUK", Hasil);
            cetakHasil(Hasil);
        }
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_tutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea_hasil;
    private javax.swing.JTextField txt_angka1;
    private javax.swing.JTextField txt_angka2;
    // End of variables declaration//GEN-END:variables
}
