/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;
import javax.swing.JOptionPane;
/**
 *
 * @author Adan Nugraha
 */
public class Menu extends javax.swing.JFrame {
    
    // membuat objek baru dari class Login yang sudah terkoneksi dengan database
    Login bb = new Login();
    /**
     * Creates new form Menu
     */
    public Menu() {
        // mengecek sudah login atau belum
        // jika belum login akan di redirect ke form login
        if ("AKTIF".equals(Session.getStatusLogin())) {
            initComponents();
            setSessionNama();
        } else {
        // menutup menu tanpa keluar dari aplikasi
        dispose();
        // memanggil form login
        LoginForm form = new LoginForm();
        form.setVisible(true);
        }
    }
    
    private void setSessionNama() {
        label_nama.setText("Hai "+Session.getNama());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        label_nama = new javax.swing.JLabel();
        label_keterangan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAplikasi = new javax.swing.JMenu();
        jMenuKeluar = new javax.swing.JMenuItem();
        jMenuCRUD = new javax.swing.JMenu();
        jMenuCRUDSiswa = new javax.swing.JMenuItem();
        jMenuPolimorfisme = new javax.swing.JMenu();
        jMenuBentuk = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nama.setText("Hai Nama User");

        label_keterangan.setText("Selamat Datang di Aplikasi Praktikum PBO");

        jMenuAplikasi.setText("Aplikasi");

        jMenuKeluar.setText("Keluar");
        jMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKeluarActionPerformed(evt);
            }
        });
        jMenuAplikasi.add(jMenuKeluar);

        jMenuBar1.add(jMenuAplikasi);

        jMenuCRUD.setText("CRUD");
        jMenuCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCRUDActionPerformed(evt);
            }
        });

        jMenuCRUDSiswa.setText("CRUD Siswa");
        jMenuCRUDSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCRUDSiswaActionPerformed(evt);
            }
        });
        jMenuCRUD.add(jMenuCRUDSiswa);

        jMenuBar1.add(jMenuCRUD);

        jMenuPolimorfisme.setText("Polimorfisme");
        jMenuPolimorfisme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPolimorfismeActionPerformed(evt);
            }
        });

        jMenuBentuk.setText("Bentuk");
        jMenuBentuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBentukActionPerformed(evt);
            }
        });
        jMenuPolimorfisme.add(jMenuBentuk);

        jMenuBar1.add(jMenuPolimorfisme);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_keterangan)
                    .addComponent(label_nama))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(label_nama)
                .addGap(18, 18, 18)
                .addComponent(label_keterangan)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKeluarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?","Warning",2) == JOptionPane.YES_OPTION){
        bb.Logout(Session.getUserID());
        System.exit(0);
        }
    }//GEN-LAST:event_jMenuKeluarActionPerformed

    private void jMenuCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCRUDActionPerformed
        // TODO add your handling code here:
        try{
        // memanggil form siswa
        Form_Siswa form = new Form_Siswa();
        form.setVisible(true);
        }catch(Exception ex){
        }
    }//GEN-LAST:event_jMenuCRUDActionPerformed

    private void jMenuBentukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBentukActionPerformed
        // TODO add your handling code here:
        try {
            // memanggil form bentuk
            BentukForm form = new BentukForm();
            form.setVisible(true);
        } catch(Exception ex) {
            
        }
    }//GEN-LAST:event_jMenuBentukActionPerformed

    private void jMenuPolimorfismeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPolimorfismeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPolimorfismeActionPerformed

    private void jMenuCRUDSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCRUDSiswaActionPerformed
        // TODO add your handling code here:
        try { 
            Form_Siswa form = new Form_Siswa();
            form.setVisible(true);
        }catch(Exception ex){
        }
    }//GEN-LAST:event_jMenuCRUDSiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenuAplikasi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBentuk;
    private javax.swing.JMenu jMenuCRUD;
    private javax.swing.JMenuItem jMenuCRUDSiswa;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuKeluar;
    private javax.swing.JMenu jMenuPolimorfisme;
    private javax.swing.JLabel label_keterangan;
    private javax.swing.JLabel label_nama;
    // End of variables declaration//GEN-END:variables
}
